# DOCX Converter Plugin Configuration
# This configuration is managed by the DOCX plugin itself

# DOCX conversion settings
docx_conversion:
  # Enable structural style inference (adds missing heading styles based on content patterns)
  enable_structural_style_inference: true
  
  # Minimum number of following paragraphs to consider when analyzing structure
  min_following_paragraphs: 3
  
  # Enable generic heading pattern matching (e.g., "HEADING 5 GM")
  generic_heading_match: true

# DOCX-specific color conversion rules
docx_color_conversion:
  color_mappings:
    # Reds
    '#ff0000': 'color-red'
    '#c00000': 'color-red'        # Word standard 'Dark Red'
    '#e74c3c': 'color-red'        # Flat UI red variant
    # Light Red
    '#ff9999': 'color-light-red'
    '#f4cccc': 'color-light-red'
    # Browns
    '#7f6000': 'color-brown'      # Word standard 'Brown'
    '#c69c6d': 'color-light-brown'
    # Greens
    '#00b050': 'color-green'      # Word standard Green
    '#008000': 'color-green'
    '#92d050': 'color-light-green'
    # Blues
    '#0070c0': 'color-blue'       # Word standard Blue
    '#5b9bd5': 'color-blue'
    '#002060': 'color-dark-blue'  # Word standard Dark Blue
    # Cyans
    '#00b0f0': 'color-cyan'
    '#00ffff': 'color-cyan'
    # Yellows / Ambers
    '#ffc000': 'color-amber'      # Word standard Orange/Amber
    '#ffff00': 'color-yellow'
    '#fff2cc': 'color-light-yellow'
    # Purples / Magentas / Violets
    '#7030a0': 'color-purple'     # Word standard Purple
    '#ff00ff': 'color-magenta'
    '#8e7cc3': 'color-violet'
    # Highlight/background mapping for Word highlights (using exact WD_COLOR_INDEX names)
    'background-yellow': 'background-color-yellow'
    'background-bright_green': 'background-color-green'
    'background-turquoise': 'background-color-cyan'
    'background-red': 'background-color-light-red'
    'background-green': 'background-color-green'
    'background-blue': 'background-color-blue'
    'background-dark_blue': 'background-color-dark-blue'
    'background-dark_red': 'background-color-light-red'
    'background-dark_yellow': 'background-color-amber'
    'background-teal': 'background-color-cyan'
    'background-violet': 'background-color-violet'
    'background-pink': 'background-color-magenta'
    'background-gray_25': 'background-color-light-gray'
    'background-gray_50': 'background-color-dark-gray'
    'background-white': 'background-color-white'
    'background-black': 'background-color-black'
  
  theme_map:
    'accent_1': 'color-blue'      # Office default Accent1 is blue (4472C4)
    'accent_2': 'color-amber'
    'accent_3': 'color-green'
    'accent_4': 'color-red'
    'accent_5': 'color-purple'
    'accent_6': 'color-cyan'
  
  # Base RGB values for theme colours (needed to resolve tint / shade)
  # Keys must correspond to theme_color.name.lower() provided by python-docx
  theme_rgb:
    accent_1: '#4472c4'
    accent_2: '#ed7d31'
    accent_3: '#a5a5a5'
    accent_4: '#ffc000'
    accent_5: '#5b9bd5'
    accent_6: '#70ad47'
  
  # HSV-based tolerance fallback
  # If a colour is NOT matched above, each rule below defines an acceptable
  #   window in HSV space (degrees 0-360, percent 0-100) that maps it to the
  #   corresponding semantic class.
  tolerance:
    color-red:
      hue: [350, 360]  # wrap-around segment –or–
      hue2: [0, 15]    # …plus initial segment 0-15°
      sat_min: 60
      val_min: 50
    color-amber:
      hue: [25, 45]
      sat_min: 60
      val_min: 60
    color-yellow:
      hue: [46, 70]
      sat_min: 40
      val_min: 70
    color-green:
      hue: [90, 155]
      sat_min: 40
      val_min: 40
    color-cyan:
      hue: [156, 200]
      sat_min: 40
      val_min: 40
    color-blue:
      hue: [201, 260]
      sat_min: 40
      val_min: 40
    color-purple:
      hue: [261, 300]
      sat_min: 30
      val_min: 35
    color-magenta:
      hue: [301, 340]
      sat_min: 50
      val_min: 50

# Heading filter UI settings
heading_filter:
  # Maximum number of active styles to display in filter panel
  max_active_styles: 5
  
  # Default exclusions for heading styles (empty by default)
  default_exclusions: []
  
  # Panel configuration
  panel:
    # Show filter panel by default
    show_by_default: true
    
    # Panel position in UI
    position: "right"